default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: notion_clone_development

test:
  <<: *default
  database: notion_clone_test
